model_list:
  - model_name: demo-openrouter
    litellm_params:
      model: os.environ/OPENROUTER_MODEL
      api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  callbacks:
    - custom_callbacks.guardrails_callback.guardrails_callback
